### ISSUE TITLE
Request from DeMiaowa Devs - Take down.

### ISSUE THREAD

**Issue by AyeTSG** [wazadev/StrayFloppa-org#2]
### Discussed in https://github.com/wazadev/StrayFloppa-org/discussions/1

<div type='discussions-op-text'>

<sup>Originally posted by **AyeTSG** February 21, 2024</sup>
Hello. Not gonna ask politely, please take this website down IMMEDIATELY! We take the scamming of our community very seriously.</div>

**Comment by wazadev** [comment]
Check updates.txt. And now shut up, please, man.

**Comment by AyeTSG** [comment]
I would prefer _not_ to have to take further action. This website was designed with the intention of collecting payment from the english-speaking Hello Street Cat community.

**Comment by AyeTSG** [comment]
You have zero permission to associate our restream, or the community wiki, with this website.

**Comment by wazadev** [comment]
I only love cats and I want others to love it😺

**Comment by wazadev** [comment]
But if you don't want me to associate the great Mr. Fresh with my website, that's fine

**Comment by AyeTSG** [comment]
I ask that you no longer link to or associate our re-stream / community wiki with your website.

**Comment by wazadev** [comment]
ok. lol

**Comment by wazadev** [comment]
now. please SHUT UP FURRY LOL

**Comment by wazadev** [comment]
sorry lol
